[project]
name = "dev-lab-setup"
version = "0.1.0"
description = "pyinfra-based automation for Linux dev lab setup"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyinfra>=3.2.0",
]

